kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
   username:
     from_secret: docker_username
   password:
     from_secret: docker_password
   repo: registry.rudin.io/x86/mapserver
   registry: registry.rudin.io
   auto_tag: true


