version: "3.6"

services:
 minetest:
  image: registry.gitlab.com/minetest/minetest/server:5.7.0
  user: root
  volumes:
   - "world_data:/root/.minetest/worlds/world"
   - "./dev/worldmods:/root/.minetest/worlds/world/worldmods"
   - "./dev/minetest.conf:/etc/minetest/minetest.conf"
   - "./dev/mapserver.json:/root/.minetest/worlds/world/mapserver.json"
  ports:
   - "30000:30000/udp"
